---
slug: test_book
filename: test_book
title: Title of the Book
subtitle: Change me
description: Change me.
author: Author Name
copyright: 2014
uuid: 8da5d7ed-8c89-4c80-8f4f-06a723754966
pdf_preview_page_range: 1..30
epub_mobi_preview_chapter_range: 0..1
